#!/usr/bin/env node
/**
 * Fetches Agroverse shipment ledger metadata from Wix CMS and writes it to
 * `data/agroverse-shipments.js` for consumption by our static pages.
 *
 * Usage:
 *   WIX_API_KEY=xxxx node scripts/syncAgroverseShipments.js
 *
 * Optional env overrides:
 *   - WIX_SITE_ID
 *   - WIX_ACCOUNT_ID
 *   - WIX_AGROVERSE_COLLECTION_ID
 */

const fs = require("fs");
const path = require("path");

const API_KEY = process.env.WIX_API_KEY;
const SITE_ID = process.env.WIX_SITE_ID || "d45a189f-d0cc-48de-95ee-30635a95385f";
const ACCOUNT_ID =
  process.env.WIX_ACCOUNT_ID || "0e2cde5f-b353-468b-9f4e-36835fc60a0e";
const COLLECTION_ID =
  process.env.WIX_AGROVERSE_COLLECTION_ID || "AgroverseShipments";

if (!API_KEY) {
  console.error("❌ Missing WIX_API_KEY environment variable.");
  console.error("   Export WIX_API_KEY (and optionally WIX_SITE_ID / WIX_ACCOUNT_ID) first.");
  process.exit(1);
}

const HEADERS = {
  Authorization: API_KEY,
  "Content-Type": "application/json",
  "wix-site-id": SITE_ID,
  "wix-account-id": ACCOUNT_ID,
};

const QUERY_URL = `https://www.wixapis.com/wix-data/v2/items/query?dataCollectionId=${COLLECTION_ID}`;
const OUTPUT_DIR = path.join(__dirname, "..", "data");
const OUTPUT_JS = path.join(OUTPUT_DIR, "agroverse-shipments.js");

async function fetchShipments() {
  const body = {
    query: {
      paging: { limit: 1000, offset: 0 },
      sort: [{ fieldName: "title", order: "ASC" }],
    },
  };

  const response = await fetch(QUERY_URL, {
    method: "POST",
    headers: HEADERS,
    body: JSON.stringify(body),
  });

  const payload = await response.json();
  if (!response.ok) {
    throw new Error(
      `Failed to query Wix collection (${response.status}): ${payload.error?.message || response.statusText}`
    );
  }

  return payload.dataItems || payload.items || [];
}

function normalizeShipments(dataItems) {
  return dataItems
    .filter((item) => item?.data?.contract_url)
    .map((item) => ({
      id: item.data?._id || item.id || item._id || null,
      title: item.data?.title || "",
      contractUrl: item.data?.contract_url || "",
      status: item.data?.status || null,
      tags: item.data?.tags || [],
      updatedDate: item.data?.updatedDate || item.updatedDate || item._updatedDate || null,
      createdDate: item.data?.createdDate || item.createdDate || item._createdDate || null,
    }));
}

function buildModule(shipments) {
  const banner = `// Auto-generated by scripts/syncAgroverseShipments.js on ${new Date().toISOString()}\n// Do not edit by hand.\n`;
  const exportLine = `export const agroverseShipments = ${JSON.stringify(shipments, null, 2)};\n`;
  return `${banner}\n${exportLine}`;
}

async function main() {
  console.log("⬇️  Fetching Agroverse shipments from Wix...");
  const dataItems = await fetchShipments();
  const shipments = normalizeShipments(dataItems);
  await fs.promises.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.promises.writeFile(OUTPUT_JS, buildModule(shipments), "utf8");
  console.log(`✅ Wrote ${shipments.length} shipments to ${OUTPUT_JS}`);
}

main().catch((err) => {
  console.error("❌ Sync failed:", err.message);
  process.exit(1);
});

